<a href="https://colab.research.google.com/github/KimDongHyun0907/Sesac_openAI/blob/main/%ED%99%9C%EC%84%B1%ED%99%94%ED%95%A8%EC%88%98_%ED%8C%8C%EB%9D%BC%EB%AF%B8%ED%84%B0%EC%99%80_%ED%9E%88%EB%93%A0%EB%A0%88%EC%9D%B4%EC%96%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
x=np.array([1,2,3,4,5,6])
y=np.array([10,98,8,2,3,4])

In [ ]:
input_layer = tf.keras.layers.InputLayer(input_shape=(1,))
hidden_layer1 = tf.keras.layers.Dense(units=4, activation='relu')
hidden_layer2 = tf.keras.layers.Dense(units=2, activation='relu')
output_layer= tf.keras.layers.Dense(units=1)
# activation이 없으면 활성화함수 wx+b가 되어있는 것임.

model = keras.Sequential([
    input_layer,
    hidden_layer1,
    hidden_layer2,
    output_layer
    ])


In [ ]:
modelvalue = model.weights
modelvalue

[<tf.Variable 'dense_3/kernel:0' shape=(1, 4) dtype=float32, numpy=
 array([[ 0.51151574,  0.5496485 , -0.82256854, -0.24861354]],
       dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_4/kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[-0.8105962 , -0.7117398 ],
        [ 0.32767797, -0.67657137],
        [ 0.62613153, -0.8270757 ],
        [-0.21192837,  0.04309678]], dtype=float32)>,
 <tf.Variable 'dense_4/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'dense_5/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[-0.6801817],
        [ 1.3199507]], dtype=float32)>,
 <tf.Variable 'dense_5/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

0,1 인덱스, dense(units=4) w, b  /  x값이 6*1이므로  w는 4, b는 4  
2,3 인덱스, dense(units=2) w, b  /  w는 2, b는 2  
4,5 인덱스, dense(units=1) w, b  /  w는 1, b는 1  


In [ ]:
len(modelvalue)  # Dense층 * 2개 (dense 층마다 w, b 값 있음.)

6

In [ ]:
intermediate_layer_model = tf.keras.Model(inputs=model.input, outputs=model.layers[0].output)
intermediate_output = intermediate_layer_model(x)

print(intermediate_output)

tf.Tensor(
[[0.51151574 0.5496485  0.         0.        ]
 [1.0230315  1.099297   0.         0.        ]
 [1.5345472  1.6489456  0.         0.        ]
 [2.046063   2.198594   0.         0.        ]
 [2.5575786  2.7482426  0.         0.        ]
 [3.0690944  3.2978911  0.         0.        ]], shape=(6, 4), dtype=float32)


In [ ]:
for layer in model.layers:
  print(layer.get_weights()[0])
  print(layer.get_weights()[1])
  print()

[[ 0.51151574  0.5496485  -0.82256854 -0.24861354]]
[0. 0. 0. 0.]

[[-0.8105962  -0.7117398 ]
 [ 0.32767797 -0.67657137]
 [ 0.62613153 -0.8270757 ]
 [-0.21192837  0.04309678]]
[0. 0.]

[[-0.6801817]
 [ 1.3199507]]
[0.]



In [ ]:
x=np.array([[1,2,3,4,5,6], [1,2,3,4,5,6]])

input_layer = tf.keras.layers.InputLayer(input_shape=(2,))
hidden_layer1 = tf.keras.layers.Dense(units=4, activation='relu')
hidden_layer2 = tf.keras.layers.Dense(units=2, activation='relu')
output_layer= tf.keras.layers.Dense(units=1)
# activation이 없으면 활성화함수 wx+b가 되어있는 것임.

model = keras.Sequential([
    input_layer,
    hidden_layer1,
    hidden_layer2,
    output_layer
    ])

for layer in model.layers:
  print(layer.get_weights()[0])
  print(layer.get_weights()[1])
  print()

[[ 0.21260405 -0.12014079  0.72313285 -0.26046205]
 [-0.6268585  -0.45895314 -0.6958382  -0.48734522]]
[0. 0. 0. 0.]

[[ 0.36132002  0.15954304]
 [-0.1741476  -0.8272519 ]
 [ 0.53552437  0.02090907]
 [ 0.91135263  0.7908926 ]]
[0. 0.]

[[0.8205563 ]
 [0.48994398]]
[0.]

