In [ ]:
import numpy as np
x = np.array([1,2,1,1,1,2,2,1,1])
y = np.array([100,200,100,50,10,20,20,10,10])
len(x),len(y),x.mean(), y.mean()

(9, 9, 1.3333333333333333, 57.77777777777778)

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()  # 추정기 함수 활성화
model.fit(np.reshape(x,(-1,1)),y)  # w, b가 생성
model.coef_,model.intercept_

(array([33.33333333]), 13.333333333333336)

In [ ]:
w, b = model.coef_,model.intercept_
new_x = 3
new_y = new_x*w+b
new_y

array([113.33333333])

In [ ]:
new_x = 3
new_x = np.reshape(new_x, (-1,1))
model.predict(new_x)

array([113.33333333])

https://wikidocs.net/42596  
타이타닉 승객 생존 여부 분류 모델 학습

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.linear_model import LogisticRegression
import numpy as np

In [ ]:
# 데이터 로드
train_df = pd.read_excel('https://github.com/cranberryai/todak_todak_python/blob/master/machine_learning/binary_classification/%E1%84%90%E1%85%A1%E1%84%8B%E1%85%B5%E1%84%90%E1%85%A1%E1%84%82%E1%85%B5%E1%86%A8_b0fdSDZ.xlsx?raw=true', sheet_name='train')
test_df = pd.read_excel('https://github.com/cranberryai/todak_todak_python/blob/master/machine_learning/binary_classification/%E1%84%90%E1%85%A1%E1%84%8B%E1%85%B5%E1%84%90%E1%85%A1%E1%84%82%E1%85%B5%E1%86%A8_b0fdSDZ.xlsx?raw=true', sheet_name='test')


In [ ]:
train_df.head()

pclass                            name     sex  age  sibsp  parch   ticket  \
0       2           Lehmann, Miss. Bertha  Female   17      0      0  SC 1748   
1       3  Laitinen, Miss. Kristina Sofia  Female   37      0      0     4135   
2       3     Rosblom, Mr. Viktor Richard    Male   18      1      1   370129   
3       3               Karaic, Mr. Milan    Male   30      0      0   349246   
4       3         Moen, Mr. Sigurd Hansen    Male   25      0      0   348123   

    fare embarked  survival  
0  12.00        C         1  
1   9.59        S         0  
2  20.21        S         0  
3   7.90        S         0  
4   7.65        S         0

In [ ]:
labels = ['사망', '생존']

In [ ]:
# survival 변수와의 연관성 EDA 후에 아래 작업을 실행
# 불필요한 변수를 제거하고 survival는 y값으로 사용해야 하니 제거
x_train = train_df.drop(['name', 'ticket', 'survival'], axis=1)
x_test = test_df.drop(['name', 'ticket', 'survival'], axis=1)

In [ ]:
x_train.head()

pclass     sex  age  sibsp  parch   fare embarked
0       2  Female   17      0      0  12.00        C
1       3  Female   37      0      0   9.59        S
2       3    Male   18      1      1  20.21        S
3       3    Male   30      0      0   7.90        S
4       3    Male   25      0      0   7.65        S

In [ ]:
x_test.head()

pclass     sex  age  sibsp  parch    fare embarked
0       2  Female   21      0      1   21.00        S
1       3    Male   35      0      0    7.05        S
2       1    Male   45      1      1  134.50        C
3       2    Male   40      0      0   16.00        S
4       1  Female   55      2      0   25.70        S

In [ ]:
# 머신러닝에 들어가는 x 데이터는 문자데이터는 안됨.
# 벡터데이터야함.
# 성별은 Male은 0, Femaie은 1
# embarked를 0, 1, 2, 3, 4로 줬을 때 이 값이 순서대로 값의 크기가 의미가 있는가를 고민.
# 문자를 단순하게 숫자 0, 1, 2, 3 ...로 작성을 하지 않음. -> one hot 인코딩 작업을 진행
# x데이터는 더미변수화, y변수는 원핫인코딩
y_train = train_df['survival']
y_test = test_df['survival']

transformer = make_column_transformer(
    (OneHotEncoder(), ['pclass', 'sex', 'embarked']),  # ('pclass', 'sex', 'embarked')에 대해 One-Hot 인코딩을 수행
    remainder='passthrough')  # 지정한 열 이외의 열은 변경하지 않고 그대로 유지
transformer.fit(x_train)
x_train = transformer.transform(x_train)
x_test = transformer.transform(x_test)

In [ ]:
x_train[0]

array([ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  0., 17.,  0.,  0., 12.])

In [ ]:
model = LogisticRegression()
model.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
print(model.score(x_train, y_train))

0.7945205479452054


In [ ]:
print(model.score(x_test, y_test))

0.7763578274760383


In [ ]:
model.predict(x_test)  # 위에 있는 77%는 이 결과값의 1, 0, 0 값하고 y_train 값하고의 일치율이 77%

array([1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,

In [ ]:
model.predict_proba(x_test)

array([[0.13246736, 0.86753264],
       [0.90265405, 0.09734595],
       [0.60918187, 0.39081813],
       [0.82355928, 0.17644072],
       [0.35993094, 0.64006906],
       [0.53494048, 0.46505952],
       [0.14057448, 0.85942552],
       [0.92093132, 0.07906868],
       [0.04752197, 0.95247803],
       [0.81807013, 0.18192987],
       [0.44198026, 0.55801974],
       [0.07533482, 0.92466518],
       [0.81077486, 0.18922514],
       [0.86687242, 0.13312758],
       [0.29917854, 0.70082146],
       [0.79849065, 0.20150935],
       [0.36569609, 0.63430391],
       [0.89131147, 0.10868853],
       [0.80650111, 0.19349889],
       [0.84615112, 0.15384888],
       [0.63396478, 0.36603522],
       [0.89127877, 0.10872123],
       [0.23740332, 0.76259668],
       [0.21053996, 0.78946004],
       [0.92205025, 0.07794975],
       [0.30808514, 0.69191486],
       [0.54524493, 0.45475507],
       [0.95178352, 0.04821648],
       [0.84544523, 0.15455477],
       [0.23593661, 0.76406339],
       [0.

In [ ]:
## 새로운 값을 넣어 확인
newx_test = [
    [2, 'Female', 21, 0, 1, 21.00, 'S']
]
newx_test = pd.DataFrame(newx_test, columns=['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked'])
newx_test = transformer.transform(newx_test)

In [ ]:
y_predict = model.predict(newx_test)
y_predict

array([1])

In [ ]:
label = labels[y_predict[0]]
label

'생존'

In [ ]:
y_predict = model.predict_proba(newx_test)
y_predict

array([[0.13246736, 0.86753264]])

In [ ]:
confidence = y_predict[0][y_predict[0].argmax()]
confidence

0.867532641303584

In [ ]:
# 사이킷런에서 제공하는 당뇨병데이터셋 샘플 (x값한개 넣기위한 작업임, 의미없음)
from sklearn.datasets import load_diabetes
import numpy as np
diabetes = load_diabetes()  # 사이킷런 제공 데이터셋

In [ ]:
diabetes.keys()  # 구성항목 확인가능

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [ ]:
diabetes['DESCR']

'.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - age     age in years\n      - sex\n      - bmi     body mass index\n      - bp      average blood pressure\n      - s1      tc, total serum cholesterol\n      - s2      ldl, low-density lipoproteins\n      - s3      hdl, high-density lipoproteins\n      - s4      tch, total cholesterol / HDL\n      - s5      ltg, possibly log of serum triglycerides level\n      - s6      glu, blood sugar

In [ ]:
len(diabetes)

8

In [ ]:
# 한개의 x값을 갖는 인공신경망을 만들기위하여 임의로 3번째의 변수를 x값으로 할당함, 3번째변수 의미없는 값임
x = diabetes.data[:, 2]
y = diabetes.target

np.shape(x), np.shape(y)  # x,y 데이터갯수 같아야함.

((442,), (442,))

In [ ]:
## 사이킷런 머신러닝이면 모델만 결정하면 됨.
# 전처리 필요없음. x값의 숫자화(벡터화). 정규화(표준화) 다 되어 있음.
# 예측(회귀분석) wx+b를 계산하는 회귀분석 모델만 선택하면 됨.
# 어떤 모델을 사용할 것인가, 그 모델의 설명력만 작업만

In [ ]:
xx = [[1,2,3],
      [2,2,3],
      [2,2,3],
      [2,3,4]]
w = [[10, 11, 12, 13],
     [20, 21, 22, 23],
     [30, 31, 32, 33]]

b=[100, 0, 0, 0]

xx=np.array(xx); w=np.array(w)
np.shape(xx), np.shape(w)

((4, 3), (3, 4))

In [ ]:
yhat=[]
for x in range(4):
  yhat.append(np.dot(xx,w[:,x])+b[x])
yhat

[array([240, 250, 250, 300]),
 array([146, 157, 157, 209]),
 array([152, 164, 164, 218]),
 array([158, 171, 171, 227])]